[target.aarch64-linux-android]
linker = "C:\\Users\\c\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.14206865\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android35-clang.cmd"
rustflags = [
    "-C", "link-arg=-lc",
    "-C", "link-arg=-lm",
    "-C", "link-arg=-ldl",
    "-C", "link-arg=-llog",
    "-C", "link-arg=-landroid",
]

[env]
CC_aarch64-linux-android = "C:\\Users\\c\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.14206865\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android35-clang.cmd"
AR_aarch64-linux-android = "C:\\Users\\c\\AppData\\Local\\Android\\Sdk\\ndk\\29.0.14206865\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\llvm-ar.exe"